version: '3'

services:
  netflix-eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: bluesky-cloud-parent/bluesky-cloud-netflix-eureka-server/target/bluesky-cloud-netflix-eureka-server-0.0.1-SNAPSHOT.jar
#    image: luversof/bluesky-cloud-netflix-eureka-server
    ports:
      - '8761:8761'
    environment:
      - SPRING_PROFILES_ACTIVE=dockerdev

  config-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: bluesky-cloud-parent/bluesky-cloud-config-server/target/bluesky-cloud-config-server-0.0.1-SNAPSHOT.jar
#    image: luversof/bluesky-cloud-config-server
    ports:
      - '8888:8888'
    environment:
      - SPRING_PROFILES_ACTIVE=dockerdev
    depends_on:
      - netflix-eureka-server
      
  admin-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: bluesky-cloud-parent/bluesky-cloud-admin-server/target/bluesky-cloud-admin-server-0.0.1-SNAPSHOT.jar
#    image: luversof/bluesky-cloud-admin-server
    ports:
      - '8889:8889'
    environment:
      - SPRING_PROFILES_ACTIVE=dockerdev
    depends_on:
      - netflix-eureka-server