apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluesky-cloud-netflix-eureka-server-deployment
  labels:
    app: bluesky-cloud-netflix-eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluesky-cloud-netflix-eureka-server
  template:
    metadata:
      labels:
        app: bluesky-cloud-netflix-eureka-server
    spec:
#      hostname: netflix-eureka-server
      containers:
      - name: spring
#        image: luversof/bluesky-cloud-netflix-eureka-server:latest
        image: localhost:8083/luversof/bluesky-cloud-netflix-eureka-server:latest
#        imagePullPolicy: Never
        lifecycle:
          postStart:
            exec:
              command: ["mv", "/app.jar", "/test/app.jar"]
        volumeMounts:
        - name: app-volume
          mountPath: /test
      - name: java
        image: openjdk:11-jre-slim
        volumeMounts:
        - name: app-volume
          mountPath: /test
        command: ["java", "-Dspring.profiles.active=k8sdev", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/test/app.jar"]
#        args: ["--spring.profiles.active=k8sdev"]
        ports:
        - containerPort: 8761
      volumes:
      - name: app-volume
        emptyDir: {}
#      imagePullSecrets:
#      - name: bluesky-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bluesky-cloud-netflix-eureka-server-service
spec:
  selector:
    app: bluesky-cloud-netflix-eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
