server:
  port: 8888
spring:
  application:
    name: bluesky-cloud-config-server
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/luversof/bluesky-config-repo
          default-label: develop
    bus:
      enabled: false
