server:
  port: 8888
spring:
  config.import: classpath:/config/bootstrap.yml
  application:
    name: bluesky-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luversof/bluesky-config-repo
          default-label: develop
    bus:
      enabled: false

debug: true