server:
  port: 8888

spring:
  config.import: classpath:/config/bootstrap.yml
  application.name: bluesky-cloud-config-server
  cloud:
    config:
#      enabled: false
      fail-fast: true
      server:
        git:
          uri: https://github.com/luversof/bluesky-config-repo
          default-label: develop
    bus:
      enabled: false

debug: true


encrypt:
  keyStore:
    location: classpath:/bluesky.jks
    password: blueskyPass
    alias: bluesky-Project
    secret: blueskyPass

