DROP TABLE IF EXISTS "PROPERTIES";

CREATE TABLE "PROPERTIES" (
	"APPLICATION" VARCHAR(50) NOT NULL DEFAULT 'application',
	"PROFILE" VARCHAR(50),
	"LABEL" VARCHAR(50) NOT NULL DEFAULT 'master',
	"KEY" VARCHAR(256) NOT NULL,
	"VALUE" VARCHAR(1024) NOT NULL
);

CREATE INDEX UIX_PROPERTIES ON "PROPERTIES" ("APPLICATION", "PROFILE", "LABEL", "KEY");
