DROP DATABASE IF EXISTS `spring_config`;

CREATE DATABASE `spring_config`;

USE `spring_config`;

DROP TABLE IF EXISTS `PROPERTIES`;

CREATE TABLE `PROPERTIES` (
	`APPLICATION` VARCHAR(50) NOT NULL DEFAULT 'application',
	`PROFILE` VARCHAR(50),
	`LABEL` VARCHAR(50) NOT NULL DEFAULT 'master',
	`KEY` VARCHAR(256) NOT NULL,
	`VALUE` VARCHAR(1024) NOT NULL,
	INDEX `UIX_PROPERTIES` (`APPLICATION`, `PROFILE`, `LABEL`, `KEY`) USING BTREE
);