spring:
  cloud:
    gateway:
      routes:
      - id: bluesky-api-bookkeeping-service
        uri: lb://BLUESKY-API-BOOKKEEPING-SERVICE
        predicates:
        - Path=/api/bookkeeping/**
      - id: bluesky-api-user-service
        uri: lb://BLUESKY-API-USER-SERVICE
        predicates:
        - Path=/api/user/**