spring:
  cloud:
    gateway:
      routes:
      - id: bluesky-api-bookkeeping
        uri: lb://bluesky-api-bookkeeping
        predicates:
        - Path=/api/bookkeeping,/api/bookkeeping/**
      - id: bluesky-api-user
        uri: lb://bluesky-api-user
        predicates:
        - Path=/api/user,/api/user/**