spring:
  cloud:
    gateway:
      server.webflux.routes:
      - id: bluesky-api-blog
        uri: lb://bluesky-api-blog-service
        predicates:
        - Host=blog.api.bluesky.local
      - id: bluesky-api-board
        uri: lb://bluesky-api-board-service
        predicates:
        - Host=board.api.bluesky.local
      - id: bluesky-api-bookkeeping
        uri: lb://bluesky-api-bookkeeping-service
        predicates:
        - Host=bookkeeping.api.bluesky.local
      - id: bluesky-api-stock
        uri: lb://bluesky-api-stock-service
        predicates:
        - Host=stock.api.bluesky.local
      - id: bluesky-api-user
        uri: lb://bluesky-api-user-service
        predicates:
        - Host=user.api.bluesky.local
      - id: bluesky-cloud-admin-server
        uri: lb://bluesky-cloud-admin-server-service
        predicates:
        - Host=admin.cloud.bluesky.local
      - id: bluesky-cloud-config-server
        uri: lb://bluesky-cloud-config-server-service
        predicates:
        - Host=config.cloud.bluesky.local
      - id: bluesky-cloud-netflix-eureka-server-1
        uri: lb://bluesky-cloud-config-server-1-service
        predicates:
        - Host=eureka1.cloud.bluesky.local
      - id: bluesky-cloud-netflix-eureka-server-2
        uri: lb://bluesky-cloud-config-server-2-service
        predicates:
        - Host=eureka2.cloud.bluesky.local
      - id: bluesky-web-gate
        uri: lb://bluesky-web-gate-service
        predicates:
        - Host=gate.web.bluesky.local
      - id: bluesky-web-swagger-ui
        uri: lb://bluesky-web-swagger-ui-service
        predicates:
        - Host=swagger.web.bluesky.local