spring:
  cloud:
    gateway:
      server.webflux.routes:
      - id: bluesky-api-blog
        uri: https://blog.api.bluesky.local
        predicates:
        - Host=blog.api.bluesky.local
      - id: bluesky-api-board
        uri: https://board.api.bluesky.local
        predicates:
        - Host=board.api.bluesky.local
      - id: bluesky-api-bookkeeping
        uri: https://bookkeeping.api.bluesky.local
        predicates:
        - Host=bookkeeping.api.bluesky.local
      - id: bluesky-api-poe
        uri: https://poe.api.bluesky.local
        predicates:
        - Host=poe.api.bluesky.local
      - id: bluesky-api-stock
        uri: https://stock.api.bluesky.local
        predicates:
        - Host=stock.api.bluesky.local
      - id: bluesky-api-user
        uri: https://user.api.bluesky.local
        predicates:
        - Host=user.api.bluesky.local
      - id: bluesky-cloud-admin-server
        uri: https://admin.cloud.bluesky.local
        predicates:
        - Host=admin.cloud.bluesky.local
      - id: bluesky-cloud-config-server
        uri: https://config.cloud.bluesky.local
        predicates:
        - Host=config.cloud.bluesky.local
      - id: bluesky-cloud-netflix-eureka-server-1
        uri: https://eureka1.cloud.bluesky.local
        predicates:
        - Host=eureka1.cloud.bluesky.local
      - id: bluesky-cloud-netflix-eureka-server-2
        uri: https://eureka2.cloud.bluesky.local
        predicates:
        - Host=eureka2.cloud.bluesky.local
      - id: bluesky-web-gate
        uri: https://gate.web.bluesky.local
        predicates:
        - Host=gate.web.bluesky.local
      - id: bluesky-web-swagger-ui
        uri: https://swagger.web.bluesky.local
        predicates:
        - Host=swagger.web.bluesky.local