spring:
  cloud:
    gateway:
      server.webflux.routes:
      - id: bluesky-api-blog
        uri: lb://bluesky-api-blog-service
        predicates:
        - Host=blog.api.bluesky.local
      - id: bluesky-api-board
        uri: lb://bluesky-api-board-service
        predicates:
        - Host=board.api.bluesky.local
      - id: bluesky-api-bookkeeping
        uri: lb://bluesky-api-bookkeeping-service
        predicates:
        - Host=bookkeeping.api.bluesky.local
      - id: bluesky-api-stock
        uri: lb://bluesky-api-stock-service
        predicates:
        - Host=stock.api.bluesky.local
      - id: bluesky-api-user
        uri: lb://bluesky-api-user-service
        predicates:
        - Host=user.api.bluesky.local