server:
  port: 8761
spring:
  config.import: classpath:/config/bootstrap.yml
  application:
    name: bluesky-cloud-netflix-eureka-server

eureka:
  client:
#    register-with-eureka: false
    fetch-registry: false
    